#include "ShutdownTab.CommandsTab.h"

ShutdownCommandsTab::ShutdownCommandsTab() : Gtk::Box(Gtk::ORIENTATION_VERTICAL, 5) {
    set_margin_left(10);
    set_margin_top(10);
    auto* r = Gtk::manage(new Gtk::Box(Gtk::ORIENTATION_HORIZONTAL, 5));
    auto* l = Gtk::manage(new Gtk::Label("Shutdown:"));
    l->set_size_request(100, -1);
    shutdownCmdEntry = Gtk::manage(new Gtk::Entry());
    shutdownCmdEntry->set_text("/sbin/shutdown -h now");
    shutdownCmdEntry->set_hexpand(true);
    r->pack_start(*l, Gtk::PACK_SHRINK);
    r->pack_start(*shutdownCmdEntry, Gtk::PACK_EXPAND_WIDGET);
    pack_start(*r, Gtk::PACK_SHRINK);
    auto* r2 = Gtk::manage(new Gtk::Box(Gtk::ORIENTATION_HORIZONTAL, 5));
    auto* l2 = Gtk::manage(new Gtk::Label("Reboot:"));
    l2->set_size_request(100, -1);
    rebootCmdEntry = Gtk::manage(new Gtk::Entry());
    rebootCmdEntry->set_text("/sbin/shutdown -r now");
    rebootCmdEntry->set_hexpand(true);
    r2->pack_start(*l2, Gtk::PACK_SHRINK);
    r2->pack_start(*rebootCmdEntry, Gtk::PACK_EXPAND_WIDGET);
    pack_start(*r2, Gtk::PACK_SHRINK);
    auto* r3 = Gtk::manage(new Gtk::Box(Gtk::ORIENTATION_HORIZONTAL, 5));
    auto* l3 = Gtk::manage(new Gtk::Label("Suspend:"));
    l3->set_size_request(100, -1);
    suspendCmdEntry = Gtk::manage(new Gtk::Entry());
    suspendCmdEntry->set_text("systemctl suspend");
    suspendCmdEntry->set_hexpand(true);
    r3->pack_start(*l3, Gtk::PACK_SHRINK);
    r3->pack_start(*suspendCmdEntry, Gtk::PACK_EXPAND_WIDGET);
    pack_start(*r3, Gtk::PACK_SHRINK);
    auto* r4 = Gtk::manage(new Gtk::Box(Gtk::ORIENTATION_HORIZONTAL, 5));
    auto* l4 = Gtk::manage(new Gtk::Label("Hibernate:"));
    l4->set_size_request(100, -1);
    hibernateCmdEntry = Gtk::manage(new Gtk::Entry());
    hibernateCmdEntry->set_text("systemctl hibernate");
    hibernateCmdEntry->set_hexpand(true);
    r4->pack_start(*l4, Gtk::PACK_SHRINK);
    r4->pack_start(*hibernateCmdEntry, Gtk::PACK_EXPAND_WIDGET);
    pack_start(*r4, Gtk::PACK_SHRINK);
    auto* r5 = Gtk::manage(new Gtk::Box(Gtk::ORIENTATION_HORIZONTAL, 5));
    auto* l5 = Gtk::manage(new Gtk::Label("Lock:"));
    l5->set_size_request(100, -1);
    lockCmdEntry = Gtk::manage(new Gtk::Entry());
    lockCmdEntry->set_text("xscreensaver-command -lock");
    lockCmdEntry->set_hexpand(true);
    r5->pack_start(*l5, Gtk::PACK_SHRINK);
    r5->pack_start(*lockCmdEntry, Gtk::PACK_EXPAND_WIDGET);
    pack_start(*r5, Gtk::PACK_SHRINK);
    auto* r6 = Gtk::manage(new Gtk::Box(Gtk::ORIENTATION_HORIZONTAL, 5));
    auto* l6 = Gtk::manage(new Gtk::Label("Clock:"));
    l6->set_size_request(100, -1);
    clockCmdEntry = Gtk::manage(new Gtk::Entry());
    clockCmdEntry->set_text("xclock");
    clockCmdEntry->set_hexpand(true);
    r6->pack_start(*l6, Gtk::PACK_SHRINK);
    r6->pack_start(*clockCmdEntry, Gtk::PACK_EXPAND_WIDGET);
    pack_start(*r6, Gtk::PACK_SHRINK);
    auto* r7 = Gtk::manage(new Gtk::Box(Gtk::ORIENTATION_HORIZONTAL, 5));
    auto* l7 = Gtk::manage(new Gtk::Label("Mail:"));
    l7->set_size_request(100, -1);
    mailCmdEntry = Gtk::manage(new Gtk::Entry());
    mailCmdEntry->set_text("thunderbird");
    mailCmdEntry->set_hexpand(true);
    r7->pack_start(*l7, Gtk::PACK_SHRINK);
    r7->pack_start(*mailCmdEntry, Gtk::PACK_EXPAND_WIDGET);
    pack_start(*r7, Gtk::PACK_SHRINK);
    auto* r8 = Gtk::manage(new Gtk::Box(Gtk::ORIENTATION_HORIZONTAL, 5));
    auto* l8 = Gtk::manage(new Gtk::Label("Run:"));
    l8->set_size_request(100, -1);
    runCmdEntry = Gtk::manage(new Gtk::Entry());
    runCmdEntry->set_text("xterm");
    runCmdEntry->set_hexpand(true);
    r8->pack_start(*l8, Gtk::PACK_SHRINK);
    r8->pack_start(*runCmdEntry, Gtk::PACK_EXPAND_WIDGET);
    pack_start(*r8, Gtk::PACK_SHRINK);
}

void ShutdownCommandsTab::setDefaults() {
    shutdownCmdEntry->set_text("/sbin/shutdown -h now");
    rebootCmdEntry->set_text("/sbin/shutdown -r now");
    suspendCmdEntry->set_text("systemctl suspend");
    hibernateCmdEntry->set_text("systemctl hibernate");
    lockCmdEntry->set_text("xscreensaver-command -lock");
    clockCmdEntry->set_text("xclock");
    mailCmdEntry->set_text("thunderbird");
    runCmdEntry->set_text("xterm");
}
